### ISSUE TITLE
uninitialized constant G5Authenticatable::TokenValidator

### ISSUE THREAD

**Issue by perryqh** [G5/g5_authenticatable#38]
Upgrading to 0.4.2 to 0.7.1 results in the error above.

I'm checking for API requests with:
```
 def is_api_request?
    !G5Authenticatable::TokenValidator.new(params, headers).access_token.nil?
  end
```

**Comment by maeve** [comment]
There was some minor refactoring to the service objects provided by [g5_authenticatable_api](https://github.com/G5/g5_authenticatable_api). The class you are using is now called [`G5AuthenticatableApi::Services::TokenValidator`](https://github.com/G5/g5_authenticatable_api/blob/master/lib/g5_authenticatable_api/services/token_validator.rb), with the same method signatures. If you're not actually using any of the validation logic, you could use the base class [`G5AuthenticatableApi::Services::TokenInfo`](https://github.com/G5/g5_authenticatable_api/blob/master/lib/g5_authenticatable_api/services/token_info.rb) if you prefer.

I didn't realize that the TokenValidator was being used directly by any of the client applications. I'll make sure to add a note to the CHANGELOG in both g5_authenticatable and g5_authenticatable_api about the potentially backwards incompatible change.

**Comment by perryqh** [comment]
We are using the is_api_request? in our before_filters:
```
    before_filter :authenticate_api_user!, if: :is_api_request?
    before_filter :authenticate_user!, unless: :is_api_request?
```
Is this the best approach @maeve?

**Comment by maeve** [comment]
@perryqh Yes, you do need to differentiate between API and non-API requests to determine the appropriate response when the user is not authenticated (the `authenticate_user!` filter will redirect to the auth server to display the login form, while `authenticate_api_user!` returns a 401 response).

However, the implementation of that check is app-specific - the common case would be to switch off based on the request format (e.g. JSON is an API request; HTML is a request from an end user within a browser). However, G5 has some apps that emit HTML microformats for all requests (e.g. the g5-hub), so in those cases, it is trickier to determine whether a particular request is from an API client or an end user who can respond to the redirects appropriately.
